/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IConsensusEngine } from "./IConsensusEngine";
export type { INodeManager } from "./INodeManager";
export type { IQuantlinkOracle } from "./IQuantlinkOracle";
